# Generated by Django 5.0.6 on 2024-07-17 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('album_song_creation', '0002_playlist_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('file', models.FileField(upload_to='song_files/')),
                ('album', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='album_song_creation.playlist')),
            ],
        ),
    ]
