# Generated by Django 5.0.6 on 2024-11-20 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('album_creation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('author', models.CharField(max_length=60)),
                ('file', models.FileField(upload_to='song_files/')),
                ('duration', models.CharField(max_length=30, null=True)),
                ('duration_in_seconds', models.CharField(max_length=30, null=True)),
                ('album', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='album_creation.playlist')),
            ],
        ),
    ]
