# Generated by Django 5.0.6 on 2024-07-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_creation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='author',
            field=models.CharField(default=1, max_length=60),
        ),
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
