# Generated by Django 5.0.6 on 2024-11-29 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_creation', '0003_alter_playlist_logo'),
        ('song_creation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='album_creation.playlist'),
        ),
    ]
