# Generated by Django 5.0.6 on 2024-07-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_creation', '0002_song_author_alter_song_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='author',
            field=models.CharField(max_length=60),
        ),
    ]
