# Generated by Django 5.0.6 on 2024-07-31 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_creation', '0003_alter_song_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.CharField(default='1', max_length=30),
            preserve_default=False,
        ),
    ]
