# Generated by Django 5.0.6 on 2024-08-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_creation', '0005_alter_song_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='duration_in_seconds',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
