# Generated by Django 5.0.6 on 2024-12-16 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentpost',
            options={'ordering': ['-created_at']},
        ),
    ]
