# Generated by Django 5.0.6 on 2024-11-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_forumpost_hide_upvotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentpost',
            name='hide_upvotes',
            field=models.BooleanField(default=False),
        ),
    ]
