# Generated by Django 5.0.6 on 2024-11-23 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_commentpost_hide_upvotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentpost',
            name='hide_upvotes',
        ),
        migrations.RemoveField(
            model_name='forumpost',
            name='hide_upvotes',
        ),
    ]
