# Generated by Django 5.0.6 on 2024-11-27 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_remove_commentpost_upvotes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumpost',
            options={'ordering': ['-created_at']},
        ),
    ]
