# Generated by Django 5.0.6 on 2024-09-11 12:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends_list', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FriendList',
            new_name='FriendRequestList',
        ),
    ]
