# Generated by Django 5.0.6 on 2024-12-19 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album_creation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='logo',
        ),
    ]
