# Generated by Django 5.0.6 on 2024-11-29 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_creation', '0002_alter_playlist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='album_logos/'),
        ),
    ]
