# Generated by Django 5.0.6 on 2024-12-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_creation', '0002_remove_playlist_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
